### ISSUE TITLE
Doesn't build with binutils 2.25

### ISSUE THREAD

**Issue by stewart-ibm** [open-power/hostboot#31]
In my working tree for updating buildroot, we have the option of going to binutils 2.25 rather than a patched 2.24, but if we enable binutils 2.25, hostboot no longer builds.

I'll update this issue with more information as my tree stabilises.

**Comment by williamspatrick** [comment]
Can you copy the build log into a gist output?  I wouldn't be surprised
if something we're using in libelf changed on us.

On Thu, Aug 20, 2015 at 03:33:43PM -0700, Stewart Smith wrote:
> In my working tree for updating buildroot, we have the option of going to binutils 2.25 rather than a patched 2.24, but if we enable binutils 2.25, hostboot no longer builds.
> 
> I'll update this issue with more information as my tree stabilises.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/open-power/hostboot/issues/31

-- 
Patrick Williams

**Comment by williamspatrick** [comment]
Might be caused by #24 too?

**Comment by stewart-ibm** [comment]
https://gist.github.com/stewart-ibm/c01c0cf3e947823c5fb9

**Comment by stewart-ibm** [comment]
The key bit seems to be:

    MAKE       runtime GEN
/home/stewart/op-build/output/build/host-binutils-2.25/bfd/libbfd.a(plugin.o): In function `try_load_plugin':
plugin.c:(.text+0x2a2): undefined reference to `dlopen'
plugin.c:(.text+0x2b8): undefined reference to `dlsym'
plugin.c:(.text+0x3f8): undefined reference to `dlerror'
collect2: error: ld returned 1 exit status
makefile:41: recipe for target 'tracehash' failed
make[8]: *** [tracehash] Error 1
../../../src/build/mkrules/passes.rules.mk:105: recipe for target '_BUILD/PASSES
/GEN/BODY' failed

**Comment by williamspatrick** [comment]
This looks like a pretty minor miss of -ldl here:

https://github.com/open-power/hostboot/blob/master/src/build/linker/makefile#L29

Can you add as a patch to op-build and see if that resolves?

On Mon, Aug 24, 2015 at 03:04:55PM -0700, Stewart Smith wrote:
> https://gist.github.com/stewart-ibm/c01c0cf3e947823c5fb9
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/open-power/hostboot/issues/31#issuecomment-134394099

-- 
Patrick Williams

**Comment by stewart-ibm** [comment]
That didn't actually help.. which is odd, but what did help was adding it to
https://github.com/open-power/hostboot/blob/master/src/build/trace/makefile#L32

and that made it build (well, at least Hostboot - haven't tried to see if anything boots yet)

**Comment by stewart-ibm** [comment]
I tell a lie, it was actually needed in both places. Pull request coming.
