### ISSUE TITLE
tracehash discards .group sections, can't link with gcc-4.9

### ISSUE THREAD

**Issue by jk-ozlabs** [open-power/hostboot#6]
Current hostboot won't build with gcc-4.9:

```
/home/jk/IBM/openpower/op-build/output/host/usr/bin/powerpc64le-buildroot-linux-gnu-ld -shared -z now -x -melf64ppc --nostdlib --sort-common -O3 -nostdlib --nostdlib --sort-common -O3 -nostdlib --nostdlib --sort-common -O3 -nostdlib --nostdlib --sort-common -O3 -nostdlib --nostdlib --sort-common -O3 -nostdlib --nostdlib --sort-common -O3 -nostdlib --nostdlib --sort-common -fPIC -Bsymbolic -Bsymbolic-functions -O3 -nostdlib --nostdlib --sort-common -fPIC -Bsymbolic -Bsymbolic-functions -O3 -nostdlib \
		   ../../../obj/modules/trace/interface.o ../../../obj/modules/trace/service.o ../../../obj/modules/trace/compdesc.o ../../../obj/modules/trace/buffer.o ../../../obj/modules/trace/bufferpage.o ../../../obj/modules/trace/daemonif.o ../../../obj/modules/trace/debug.o ../../../obj/modules/trace/assert.o ../../../obj/core/module_init.o \
	           -T ../../../src/module.ld -o ../../../img/libtrace.so
../../../obj/modules/trace/service.o:(.bss._ZGVZN9SingletonIN5TRACE13ComponentListEE8instanceEvE8instance+0x0): multiple definition of `guard variable for Singleton<TRACE::ComponentList>::instance()::instance'
../../../obj/modules/trace/interface.o:(.bss._ZGVZN9SingletonIN5TRACE13ComponentListEE8instanceEvE8instance+0x0): first defined here
../../../obj/modules/trace/service.o:(.bss._ZZN9SingletonIN5TRACE13ComponentListEE8instanceEvE8instance+0x0): multiple definition of `Singleton<TRACE::ComponentList>::instance()::instance'
../../../obj/modules/trace/interface.o:(.bss._ZZN9SingletonIN5TRACE13ComponentListEE8instanceEvE8instance+0x0): first defined here
../../../obj/modules/trace/service.o:(.bss._ZGVZN9SingletonIN5TRACE7ServiceEE8instanceEvE8instance+0x0): multiple definition of `guard variable for Singleton<TRACE::Service>::instance()::instance'
../../../obj/modules/trace/interface.o:(.bss._ZGVZN9SingletonIN5TRACE7ServiceEE8instanceEvE8instance+0x0): first defined here
../../../obj/modules/trace/service.o:(.bss._ZZN9SingletonIN5TRACE7ServiceEE8instanceEvE8instance+0x0): multiple definition of `Singleton<TRACE::Service>::instance()::instance'
../../../obj/modules/trace/interface.o:(.bss._ZZN9SingletonIN5TRACE7ServiceEE8instanceEvE8instance+0x0): first defined here
```
These duplicate templated symbols should have been unified during the link, but it looks like the tracehash tool drops the `.group` sections, which are required to coalesce these.

The input file to tracehash:

```
[jk@pablo trace]$ objdump -h service.o.trace 

service.o.trace:     file format elf64-big

Sections:
Idx Name          Size      VMA               LMA               File off  Algn
  0 .group        00000008  0000000000000000  0000000000000000  00000040  2**2
                  CONTENTS, READONLY, EXCLUDE, GROUP, LINK_ONCE_DISCARD
  1 .group        00000008  0000000000000000  0000000000000000  00000048  2**2
                  CONTENTS, READONLY, EXCLUDE, GROUP, LINK_ONCE_DISCARD
  2 .group        00000008  0000000000000000  0000000000000000  00000050  2**2
                  CONTENTS, READONLY, EXCLUDE, GROUP, LINK_ONCE_DISCARD
  3 .group        00000008  0000000000000000  0000000000000000  00000058  2**2
                  CONTENTS, READONLY, EXCLUDE, GROUP, LINK_ONCE_DISCARD
  4 .group        00000008  0000000000000000  0000000000000000  00000060  2**2
                  CONTENTS, READONLY, EXCLUDE, GROUP, LINK_ONCE_DISCARD
  5 .group        00000008  0000000000000000  0000000000000000  00000068  2**2
                  CONTENTS, READONLY, EXCLUDE, GROUP, LINK_ONCE_DISCARD
  6 .text         00000000  0000000000000000  0000000000000000  00000070  2**0
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
[...]
```
and after tracehash has run:

```
[jk@pablo trace]$ objdump -h service.o

service.o:     file format elf64-big

Sections:
Idx Name          Size      VMA               LMA               File off  Algn
  0 .text         00000000  0000000000000000  0000000000000000  00000040  2**0
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
  1 .data         00000000  0000000000000000  0000000000000000  00000040  2**0
                  CONTENTS, ALLOC, LOAD, DATA
[...]
```

**Comment by jk-ozlabs** [comment]
If I remove the `SEC_GROUP` conditional (to include the .group sections in the output file), the build fails with:

```
    LD         libtestsyslib.so
/home/jk/IBM/openpower/op-build/output/host/usr/bin/powerpc64le-buildroot-linux-gnu-ld: ../../../../obj/modules/testsyslib/testsyslib.o: invalid SHT_GROUP entry
[repeated multiple times]
/home/jk/IBM/openpower/op-build/output/host/usr/bin/powerpc64le-buildroot-linux-gnu-ld: ../../../../obj/modules/testsyslib/testsyslib.o: no group info for section .data._ZZN8TimeTest16testClockGetTimeEvE20__traceData_codeInfo_1
[and further errors]
```

So it looks like we'll actually have to process the group entries as part of the trace utility...

**Comment by jk-ozlabs** [comment]
Although, I see that the only thing that the `tracehash` tool does to the generated .o is add the `.rodata.str.fsptrace.format` section. Is this necessary on OpenPower? If not, we could alter tracehash to create the .hash file (treating the .o.trace file as read-only), and simply use objcopy to generate the final .o from the .trace. This way. we wouldn't have to mess with .group sections at all.

**Comment by geissonator** [comment]
I've been spending quite a bit of time digging on this one.  The .group section is not documented all that well and does not copy like the other sections do.  objcopy.c shows an example but it and all other examples I've found seem to depend on internal BFD functions to accomplish the copy.

The tracehash program removes the long text strings that are associated with the traces in Hostboot.  It reduces the overall size of the hostboot image by quite a bit so it's needed for things to continue to fit in the long term.  

One prior solution we had was to do the string removal during the beginning of the compile process but that limited us in other areas.  

I sent a message out to the binutils mailing list asking for some help on this one since I'm a bit stumped.  I'll talk with Patrick about some potential workarounds since this has been dragging on for so long.

**Comment by jk-ozlabs** [comment]
Here's the op-build `.config` I'm using for LE, if you'd like to build locally:

  https://gist.github.com/jk-ozlabs/31922a248ea4b9018c64 

If you want to keep separate op-build object dirs, you can update the `op-build` alias to use a different directory for the `O=` argument.

**Comment by williamspatrick** [comment]
This is resolved, right?

**Comment by geissonator** [comment]
Yes, fixed in this commit - https://github.com/open-power/hostboot/commit/4cc2019545300c360258b5d60e358ce91cc13efd

**Comment by geissonator** [comment]
Closed via https://github.com/open-power/hostboot/commit/4cc2019545300c360258b5d60e358ce91cc13efd
